# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Projet_4_OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Projet_4_OC
    pod 'SwiftLint'
end
